#!/usr/bin/env python3
"""
Product Analysis Script
Generated by Generic Agent
"""

import pandas as pd
import json

def analyze_products(csv_file):
    """Analyze product data from CSV file."""
    df = pd.read_csv(csv_file)
    
    # Basic statistics
    total_products = len(df)
    avg_price = df['Price'].mean()
    total_value = (df['Price'] * df['Stock']).sum()
    
    # Category analysis
    category_stats = df.groupby('Category').agg({
        'Product': 'count',
        'Price': 'mean',
        'Stock': 'sum'
    }).rename(columns={'Product': 'count', 'Price': 'avg_price', 'Stock': 'total_stock'})
    
    # Low stock items
    low_stock = df[df['Stock'] < 25][['Product', 'Category', 'Stock']]
    
    return {
        'total_products': total_products,
        'average_price': float(avg_price),
        'total_inventory_value': float(total_value),
        'category_stats': category_stats.to_dict(),
        'low_stock_items': low_stock.to_dict('records')
    }

if __name__ == "__main__":
    results = analyze_products("products.csv")
    print(json.dumps(results, indent=2))
