#!/usr/bin/env python3
"""
Employee Data Analysis Script
Generated by AI Agent
"""

import pandas as pd
import matplotlib.pyplot as plt

def analyze_employees(file_path):
    """Analyze employee data."""
    df = pd.read_csv(file_path)
    
    print("Employee Data Analysis:")
    print(f"Total employees: {len(df)}")
    print(f"Average salary: ${df['salary'].mean():,.2f}")
    print(f"Average age: {df['age'].mean():.1f}")
    
    # City distribution
    city_counts = df['city'].value_counts()
    print("\nEmployees by city:")
    for city, count in city_counts.items():
        print(f"  {city}: {count}")
    
    # Salary by city
    salary_by_city = df.groupby('city')['salary'].mean()
    print("\nAverage salary by city:")
    for city, avg_salary in salary_by_city.items():
        print(f"  {city}: ${avg_salary:,.2f}")
    
    return df

if __name__ == "__main__":
    data = analyze_employees("employees.csv")
